/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the \"License\");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an \"AS IS\" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: /usr/src/github.com/ROCm/device-metrics-exporter/pkg/amdgpu//gen/amdgpu/gpu_grpc.pb.go

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"

	amdgpu "github.com/ROCm/device-metrics-exporter/pkg/amdgpu/gen/amdgpu"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGPUSvcClient is a mock of GPUSvcClient interface.
type MockGPUSvcClient struct {
	ctrl     *gomock.Controller
	recorder *MockGPUSvcClientMockRecorder
}

// MockGPUSvcClientMockRecorder is the mock recorder for MockGPUSvcClient.
type MockGPUSvcClientMockRecorder struct {
	mock *MockGPUSvcClient
}

// NewMockGPUSvcClient creates a new mock instance.
func NewMockGPUSvcClient(ctrl *gomock.Controller) *MockGPUSvcClient {
	mock := &MockGPUSvcClient{ctrl: ctrl}
	mock.recorder = &MockGPUSvcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUSvcClient) EXPECT() *MockGPUSvcClientMockRecorder {
	return m.recorder
}

// GPUGet mocks base method.
func (m *MockGPUSvcClient) GPUGet(ctx context.Context, in *amdgpu.GPUGetRequest, opts ...grpc.CallOption) (*amdgpu.GPUGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GPUGet", varargs...)
	ret0, _ := ret[0].(*amdgpu.GPUGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUGet indicates an expected call of GPUGet.
func (mr *MockGPUSvcClientMockRecorder) GPUGet(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUGet", reflect.TypeOf((*MockGPUSvcClient)(nil).GPUGet), varargs...)
}

// GPUReset mocks base method.
func (m *MockGPUSvcClient) GPUReset(ctx context.Context, in *amdgpu.GPUResetRequest, opts ...grpc.CallOption) (*amdgpu.GPUResetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GPUReset", varargs...)
	ret0, _ := ret[0].(*amdgpu.GPUResetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUReset indicates an expected call of GPUReset.
func (mr *MockGPUSvcClientMockRecorder) GPUReset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUReset", reflect.TypeOf((*MockGPUSvcClient)(nil).GPUReset), varargs...)
}

// GPUUpdate mocks base method.
func (m *MockGPUSvcClient) GPUUpdate(ctx context.Context, in *amdgpu.GPUUpdateRequest, opts ...grpc.CallOption) (*amdgpu.GPUUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GPUUpdate", varargs...)
	ret0, _ := ret[0].(*amdgpu.GPUUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUUpdate indicates an expected call of GPUUpdate.
func (mr *MockGPUSvcClientMockRecorder) GPUUpdate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUUpdate", reflect.TypeOf((*MockGPUSvcClient)(nil).GPUUpdate), varargs...)
}

// MockGPUSvcServer is a mock of GPUSvcServer interface.
type MockGPUSvcServer struct {
	ctrl     *gomock.Controller
	recorder *MockGPUSvcServerMockRecorder
}

// MockGPUSvcServerMockRecorder is the mock recorder for MockGPUSvcServer.
type MockGPUSvcServerMockRecorder struct {
	mock *MockGPUSvcServer
}

// NewMockGPUSvcServer creates a new mock instance.
func NewMockGPUSvcServer(ctrl *gomock.Controller) *MockGPUSvcServer {
	mock := &MockGPUSvcServer{ctrl: ctrl}
	mock.recorder = &MockGPUSvcServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUSvcServer) EXPECT() *MockGPUSvcServerMockRecorder {
	return m.recorder
}

// GPUGet mocks base method.
func (m *MockGPUSvcServer) GPUGet(arg0 context.Context, arg1 *amdgpu.GPUGetRequest) (*amdgpu.GPUGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUGet", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.GPUGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUGet indicates an expected call of GPUGet.
func (mr *MockGPUSvcServerMockRecorder) GPUGet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUGet", reflect.TypeOf((*MockGPUSvcServer)(nil).GPUGet), arg0, arg1)
}

// GPUReset mocks base method.
func (m *MockGPUSvcServer) GPUReset(arg0 context.Context, arg1 *amdgpu.GPUResetRequest) (*amdgpu.GPUResetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUReset", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.GPUResetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUReset indicates an expected call of GPUReset.
func (mr *MockGPUSvcServerMockRecorder) GPUReset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUReset", reflect.TypeOf((*MockGPUSvcServer)(nil).GPUReset), arg0, arg1)
}

// GPUUpdate mocks base method.
func (m *MockGPUSvcServer) GPUUpdate(arg0 context.Context, arg1 *amdgpu.GPUUpdateRequest) (*amdgpu.GPUUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GPUUpdate", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.GPUUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GPUUpdate indicates an expected call of GPUUpdate.
func (mr *MockGPUSvcServerMockRecorder) GPUUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GPUUpdate", reflect.TypeOf((*MockGPUSvcServer)(nil).GPUUpdate), arg0, arg1)
}

// mustEmbedUnimplementedGPUSvcServer mocks base method.
func (m *MockGPUSvcServer) mustEmbedUnimplementedGPUSvcServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedGPUSvcServer")
}

// mustEmbedUnimplementedGPUSvcServer indicates an expected call of mustEmbedUnimplementedGPUSvcServer.
func (mr *MockGPUSvcServerMockRecorder) mustEmbedUnimplementedGPUSvcServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedGPUSvcServer", reflect.TypeOf((*MockGPUSvcServer)(nil).mustEmbedUnimplementedGPUSvcServer))
}

// MockUnsafeGPUSvcServer is a mock of UnsafeGPUSvcServer interface.
type MockUnsafeGPUSvcServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeGPUSvcServerMockRecorder
}

// MockUnsafeGPUSvcServerMockRecorder is the mock recorder for MockUnsafeGPUSvcServer.
type MockUnsafeGPUSvcServerMockRecorder struct {
	mock *MockUnsafeGPUSvcServer
}

// NewMockUnsafeGPUSvcServer creates a new mock instance.
func NewMockUnsafeGPUSvcServer(ctrl *gomock.Controller) *MockUnsafeGPUSvcServer {
	mock := &MockUnsafeGPUSvcServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeGPUSvcServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeGPUSvcServer) EXPECT() *MockUnsafeGPUSvcServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedGPUSvcServer mocks base method.
func (m *MockUnsafeGPUSvcServer) mustEmbedUnimplementedGPUSvcServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedGPUSvcServer")
}

// mustEmbedUnimplementedGPUSvcServer indicates an expected call of mustEmbedUnimplementedGPUSvcServer.
func (mr *MockUnsafeGPUSvcServerMockRecorder) mustEmbedUnimplementedGPUSvcServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedGPUSvcServer", reflect.TypeOf((*MockUnsafeGPUSvcServer)(nil).mustEmbedUnimplementedGPUSvcServer))
}
